name: Commit and Push

on:
  push:
    branches:
      - main

jobs:
  commit_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Commit changes
        run: |
          git clone https://rafaeldevopscursobeta:${{ secrets.SECRET_TOKEN }}@github.com/rafaeldevopscursobeta/testedois.git
          cd testedois/
          git config --local user.email "test@test.com"
          git config --local user.name "Test"          
          echo "teste workflow" > arquivo.txt
          git add .
          git commit -m "Made some changes"
          git push


