name: Commit and Push

on:
  push:
    branches:
      - main

jobs:
  commit_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Commit changes
        run: |
          git config --local user.email "devops@cursobeta.com.br"
          git config --local user.name "Argocd"
          git clone https://rafaeldevopscursobeta:${{ secrets.CBPATGHPKG001 }}@github.com/rafaeldevopscursobeta/testedois.git
          cd testedois/
          echo "teste workflow" > arquivo.txt
          git add .
          git commit -m "Made some changes"
          git push


